version: "3"

services:
  db:
    image: mysql:8.0
    container_name: mysqlContainerWp
    restart: always
    ports:
      - 3306:3306
  
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: bd_themewp
      MYSQL_DATABASE: bd_themewp
    
    volumes: 
      # //persiste bd
      - ./db:/var/lib/mysql

  wordpress:
    container_name: wpContainer

    depends_on:
      - db
    image: wordpress:latest

    ports:
      - "80:80"
    restart: always

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: bd_themewp
      WORDPRESS_DB_NAME: bd_themewp

    volumes:
      - ./wp-content/themes/theme-wp/:/var/www/html/wp-content/themes/theme-wp
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins
      - ./wp-content/uploads/:/var/www/html/wp-content/uploads

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: bd_themewp